### ISSUE TITLE
Error when more tests requested than possible

### ISSUE THREAD

**Issue by andrey-kuprianov** [informalsystems/modelator#107] opened 2021-10-11 10:41 UTC
When a user requests to enumerate some number of tests using `modelator trace -n`, which is larger than the total number of tests possible to generate, the tool errors out.

E.g. when run in the [tests/integration/tla](https://github.com/informalsystems/modelator/tree/main/modelator/tests/integration/tla) directory via the command 

```sh
modelator trace -t Test2Steps -n 100 IndicesHistoryTests.tla IndicesTests.cfg
```

There are 66 tests possible; so the user can expect this number of tests to be produced. Instead they get this

```json
{
  "status": "error",
  "result": {
    "ApalacheFailure": {
      "output": {
        "stderr": "",
        "stdout": "# APALACHE version 0.15.13 build ad76fbf\n#\n# WARNING: This tool is in the experimental stage.\n#          Please report bugs at: [https://github.com/informalsystems/apalache/issues]\n# \n# Usage statistics is ON. Thank you!\n# If you have changed your mind, disable the statistics with config --enable-stats=false.\n\nChecker options: filename=IndicesHistoryTests_Test2Steps.tla, init=, next=, inv= I@12:32:09.885\nTuning:                                                           I@12:32:10.513\nPASS #0: SanyParser                                               I@12:32:10.513\nParsing file /private/var/folders/zf/cxj_wql52054hx66w0jtbh180000gn/T/.tmpHVzCSa/IndicesHistoryTests_Test2Steps.tla\nParsing file /private/var/folders/zf/cxj_wql52054hx66w0jtbh180000gn/T/.tmpHVzCSa/IndicesHistoryTests.tla\nParsing file /private/var/folders/zf/cxj_wql52054hx66w0jtbh180000gn/T/.tmpHVzCSa/IndicesExec.tla\nParsing file /private/var/folders/zf/cxj_wql52054hx66w0jtbh180000gn/T/.tmpHVzCSa/Indices.tla\nParsing file /private/var/folders/zf/cxj_wql52054hx66w0jtbh180000gn/T/Integers.tla\nParsing file /private/var/folders/zf/cxj_wql52054hx66w0jtbh180000gn/T/FiniteSets.tla\nParsing file /private/var/folders/zf/cxj_wql52054hx66w0jtbh180000gn/T/Naturals.tla\nParsing file /private/var/folders/zf/cxj_wql52054hx66w0jtbh180000gn/T/Sequences.tla\nPASS #1: TypeCheckerSnowcat                                       I@12:32:12.607\n > Running Snowcat .::.                                           I@12:32:12.608\n > Your types are great!                                          I@12:32:13.314\n > All expressions are typed                                      I@12:32:13.315\nPASS #2: ConfigurationPass                                        I@12:32:13.507\n  > IndicesHistoryTests_Test2Steps.cfg: Loading TLC configuration I@12:32:13.512\n  > Using the init predicate TestInit from the TLC config         I@12:32:13.570\n  > Using the next predicate TestNext from the TLC config         I@12:32:13.570\n  > IndicesHistoryTests_Test2Steps.cfg: found INVARIANTS: Test2StepsNeg I@12:32:13.571\n  > Set the initialization predicate to TestInit                  I@12:32:13.573\n  > Set the transition predicate to TestNext                      I@12:32:13.573\n  > Set an invariant to Test2StepsNeg                             I@12:32:13.574\n  > Replaced CONSTANT NUM_INDICES with 4                          I@12:32:13.576\n  > Replaced CONSTANT NUM_USERS with 4                            I@12:32:13.576\nPASS #3: DesugarerPass                                            I@12:32:13.701\n  > Desugaring...                                                 I@12:32:13.701\nPASS #4: UnrollPass                                               I@12:32:13.788\n  > Unroller                                                      I@12:32:13.951\nPASS #5: InlinePass                                               I@12:32:14.082\n  > InlinerOfUserOper                                             I@12:32:14.086\n  > Wrap                                                          I@12:32:14.128\n  > CallByNameOperatorEmbedder                                    I@12:32:14.136\n  > LetInExpander                                                 I@12:32:14.157\n  > Unwrap                                                        I@12:32:14.172\n  > InlinerOfUserOper                                             I@12:32:14.178\nLeaving only relevant operators: CInitPrimed, Test2StepsNeg, TestInit, TestInitPrimed, TestNext, ViewForTestNeg I@12:32:14.190\nPASS #6: PrimingPass                                              I@12:32:14.265\n  > Introducing TestInitPrimed for TestInit'                      I@12:32:14.267\nPASS #7: VCGen                                                    I@12:32:14.319\n  > Producing verification conditions from the invariant Test2StepsNeg I@12:32:14.320\n  > Using state view ViewForTestNeg                               I@12:32:14.320\n  > VCGen produced 1 verification condition(s)                    I@12:32:14.324\nPASS #8: PreprocessingPass                                        I@12:32:14.356\n  > Before preprocessing: unique renaming                         I@12:32:14.356\n > Applying standard transformations:                             I@12:32:14.360\n  > PrimePropagation                                              I@12:32:14.360\n  > Desugarer                                                     I@12:32:14.402\n  > UniqueRenamer                                                 I@12:32:14.462\n  > Normalizer                                                    I@12:32:14.555\n  > Keramelizer                                                   I@12:32:14.603\n  > After preprocessing: UniqueRenamer                            I@12:32:14.648\nPASS #9: TransitionFinderPass                                     I@12:32:14.685\n  > Found 1 initializing transitions                              I@12:32:14.700\n  > Found 11 transitions                                          I@12:32:14.740\n  > No constant initializer                                       I@12:32:14.741\n  > Applying unique renaming                                      I@12:32:14.742\nPASS #10: OptimizationPass                                        I@12:32:14.833\n > Applying optimizations:                                        I@12:32:14.836\n  > ConstSimplifier                                               I@12:32:14.836\n  > ExprOptimizer                                                 I@12:32:14.855\n  > ConstSimplifier                                               I@12:32:14.865\nPASS #11: AnalysisPass                                            I@12:32:14.934\n > Marking skolemizable existentials and sets to be expanded...   I@12:32:14.935\n  > SkolemizationMarker                                           I@12:32:14.935\n  > ExpansionMarker                                               I@12:32:14.937\n > Running analyzers...                                           I@12:32:14.944\n  > Introduced expression grades                                  I@12:32:14.988\n  > Introduced 13 formula hints                                   I@12:32:14.989\nPASS #12: PostTypeCheckerSnowcat                                  I@12:32:14.990\n > Running Snowcat .::.                                           I@12:32:14.990\n > Your types are great!                                          I@12:32:16.070\n > All expressions are typed                                      I@12:32:16.073\nPASS #13: BoundedChecker                                          I@12:32:16.189\nState 0: Checking 1 state invariants                              I@12:32:18.416\nStep 0: picking a transition out of 1 transition(s)               I@12:32:18.452\nStep 1: Transition #0 is disabled                                 I@12:32:18.611\nState 1: Checking 1 state invariants                              I@12:32:18.714\nState 1: Checking 1 state invariants                              I@12:32:18.838\nStep 1: Transition #3 is disabled                                 I@12:32:18.979\nStep 1: Transition #4 is disabled                                 I@12:32:19.045\nState 1: Checking 1 state invariants                              I@12:32:19.104\nState 1: Checking 1 state invariants                              I@12:32:19.275\nStep 1: Transition #7 is disabled                                 I@12:32:19.386\nState 1: Checking 1 state invariants                              I@12:32:19.466\nStep 1: Transition #9 is disabled                                 I@12:32:19.593\nState 1: Checking 1 state invariants                              I@12:32:19.658\nStep 1: picking a transition out of 6 transition(s)               I@12:32:19.720\nState 2: Checking 1 state invariants                              I@12:32:19.817\nState 2: state invariant 0 violated. Check the counterexample in: counterexample1.tla, MC1.out, counterexample1.json E@12:32:19.943\nState 2: state invariant 0 violated. Check the counterexample in: counterexample2.tla, MC2.out, counterexample2.json E@12:32:20.145\nState 2: Checking 1 state invariants                              I@12:32:20.531\nState 2: state invariant 0 violated. Check the counterexample in: counterexample3.tla, MC3.out, counterexample3.json E@12:32:20.607\nState 2: state invariant 0 violated. Check the counterexample in: counterexample4.tla, MC4.out, counterexample4.json E@12:32:20.786\nState 2: state invariant 0 violated. Check the counterexample in: counterexample5.tla, MC5.out, counterexample5.json E@12:32:20.965\nState 2: state invariant 0 violated. Check the counterexample in: counterexample6.tla, MC6.out, counterexample6.json E@12:32:21.151\nState 2: state invariant 0 violated. Check the counterexample in: counterexample7.tla, MC7.out, counterexample7.json E@12:32:21.292\nState 2: state invariant 0 violated. Check the counterexample in: counterexample8.tla, MC8.out, counterexample8.json E@12:32:21.427\nState 2: state invariant 0 violated. Check the counterexample in: counterexample9.tla, MC9.out, counterexample9.json E@12:32:21.557\nState 2: Checking 1 state invariants                              I@12:32:21.873\nState 2: state invariant 0 violated. Check the counterexample in: counterexample10.tla, MC10.out, counterexample10.json E@12:32:21.954\nState 2: state invariant 0 violated. Check the counterexample in: counterexample11.tla, MC11.out, counterexample11.json E@12:32:22.142\nState 2: state invariant 0 violated. Check the counterexample in: counterexample12.tla, MC12.out, counterexample12.json E@12:32:22.297\nState 2: state invariant 0 violated. Check the counterexample in: counterexample13.tla, MC13.out, counterexample13.json E@12:32:22.439\nState 2: state invariant 0 violated. Check the counterexample in: counterexample14.tla, MC14.out, counterexample14.json E@12:32:22.628\nState 2: state invariant 0 violated. Check the counterexample in: counterexample15.tla, MC15.out, counterexample15.json E@12:32:22.811\nState 2: state invariant 0 violated. Check the counterexample in: counterexample16.tla, MC16.out, counterexample16.json E@12:32:22.977\nState 2: state invariant 0 violated. Check the counterexample in: counterexample17.tla, MC17.out, counterexample17.json E@12:32:23.117\nState 2: state invariant 0 violated. Check the counterexample in: counterexample18.tla, MC18.out, counterexample18.json E@12:32:23.254\nState 2: state invariant 0 violated. Check the counterexample in: counterexample19.tla, MC19.out, counterexample19.json E@12:32:23.393\nState 2: state invariant 0 violated. Check the counterexample in: counterexample20.tla, MC20.out, counterexample20.json E@12:32:23.548\nState 2: state invariant 0 violated. Check the counterexample in: counterexample21.tla, MC21.out, counterexample21.json E@12:32:23.708\nState 2: state invariant 0 violated. Check the counterexample in: counterexample22.tla, MC22.out, counterexample22.json E@12:32:23.949\nState 2: state invariant 0 violated. Check the counterexample in: counterexample23.tla, MC23.out, counterexample23.json E@12:32:24.101\nState 2: state invariant 0 violated. Check the counterexample in: counterexample24.tla, MC24.out, counterexample24.json E@12:32:24.247\nState 2: state invariant 0 violated. Check the counterexample in: counterexample25.tla, MC25.out, counterexample25.json E@12:32:24.430\nState 2: state invariant 0 violated. Check the counterexample in: counterexample26.tla, MC26.out, counterexample26.json E@12:32:24.566\nState 2: Checking 1 state invariants                              I@12:32:24.983\nState 2: state invariant 0 violated. Check the counterexample in: counterexample27.tla, MC27.out, counterexample27.json E@12:32:25.044\nState 2: state invariant 0 violated. Check the counterexample in: counterexample28.tla, MC28.out, counterexample28.json E@12:32:25.268\nState 2: Checking 1 state invariants                              I@12:32:25.736\nState 2: state invariant 0 violated. Check the counterexample in: counterexample29.tla, MC29.out, counterexample29.json E@12:32:25.803\nState 2: state invariant 0 violated. Check the counterexample in: counterexample30.tla, MC30.out, counterexample30.json E@12:32:26.027\nState 2: Checking 1 state invariants                              I@12:32:26.565\nState 2: state invariant 0 violated. Check the counterexample in: counterexample31.tla, MC31.out, counterexample31.json E@12:32:26.649\nState 2: state invariant 0 violated. Check the counterexample in: counterexample32.tla, MC32.out, counterexample32.json E@12:32:26.887\nState 2: state invariant 0 violated. Check the counterexample in: counterexample33.tla, MC33.out, counterexample33.json E@12:32:27.141\nState 2: state invariant 0 violated. Check the counterexample in: counterexample34.tla, MC34.out, counterexample34.json E@12:32:27.390\nState 2: state invariant 0 violated. Check the counterexample in: counterexample35.tla, MC35.out, counterexample35.json E@12:32:27.681\nState 2: state invariant 0 violated. Check the counterexample in: counterexample36.tla, MC36.out, counterexample36.json E@12:32:27.931\nState 2: state invariant 0 violated. Check the counterexample in: counterexample37.tla, MC37.out, counterexample37.json E@12:32:28.180\nState 2: state invariant 0 violated. Check the counterexample in: counterexample38.tla, MC38.out, counterexample38.json E@12:32:28.442\nState 2: state invariant 0 violated. Check the counterexample in: counterexample39.tla, MC39.out, counterexample39.json E@12:32:28.717\nState 2: state invariant 0 violated. Check the counterexample in: counterexample40.tla, MC40.out, counterexample40.json E@12:32:28.979\nState 2: Checking 1 state invariants                              I@12:32:29.507\nState 2: state invariant 0 violated. Check the counterexample in: counterexample41.tla, MC41.out, counterexample41.json E@12:32:29.586\nState 2: state invariant 0 violated. Check the counterexample in: counterexample42.tla, MC42.out, counterexample42.json E@12:32:29.882\nState 2: state invariant 0 violated. Check the counterexample in: counterexample43.tla, MC43.out, counterexample43.json E@12:32:30.159\nState 2: state invariant 0 violated. Check the counterexample in: counterexample44.tla, MC44.out, counterexample44.json E@12:32:30.428\nState 2: state invariant 0 violated. Check the counterexample in: counterexample45.tla, MC45.out, counterexample45.json E@12:32:30.698\nState 2: state invariant 0 violated. Check the counterexample in: counterexample46.tla, MC46.out, counterexample46.json E@12:32:30.978\nState 2: state invariant 0 violated. Check the counterexample in: counterexample47.tla, MC47.out, counterexample47.json E@12:32:31.239\nState 2: Checking 1 state invariants                              I@12:32:31.790\nState 2: state invariant 0 violated. Check the counterexample in: counterexample48.tla, MC48.out, counterexample48.json E@12:32:31.869\nState 2: state invariant 0 violated. Check the counterexample in: counterexample49.tla, MC49.out, counterexample49.json E@12:32:32.183\nState 2: Checking 1 state invariants                              I@12:32:32.794\nState 2: state invariant 0 violated. Check the counterexample in: counterexample50.tla, MC50.out, counterexample50.json E@12:32:32.884\nState 2: state invariant 0 violated. Check the counterexample in: counterexample51.tla, MC51.out, counterexample51.json E@12:32:33.198\nState 2: state invariant 0 violated. Check the counterexample in: counterexample52.tla, MC52.out, counterexample52.json E@12:32:33.515\nState 2: state invariant 0 violated. Check the counterexample in: counterexample53.tla, MC53.out, counterexample53.json E@12:32:33.848\nState 2: state invariant 0 violated. Check the counterexample in: counterexample54.tla, MC54.out, counterexample54.json E@12:32:34.169\nState 2: Checking 1 state invariants                              I@12:32:34.857\nState 2: state invariant 0 violated. Check the counterexample in: counterexample55.tla, MC55.out, counterexample55.json E@12:32:34.953\nState 2: state invariant 0 violated. Check the counterexample in: counterexample56.tla, MC56.out, counterexample56.json E@12:32:35.322\nState 2: Checking 1 state invariants                              I@12:32:36.041\nState 2: state invariant 0 violated. Check the counterexample in: counterexample57.tla, MC57.out, counterexample57.json E@12:32:36.133\nState 2: state invariant 0 violated. Check the counterexample in: counterexample58.tla, MC58.out, counterexample58.json E@12:32:36.590\nState 2: state invariant 0 violated. Check the counterexample in: counterexample59.tla, MC59.out, counterexample59.json E@12:32:37.019\nState 2: state invariant 0 violated. Check the counterexample in: counterexample60.tla, MC60.out, counterexample60.json E@12:32:37.468\nState 2: state invariant 0 violated. Check the counterexample in: counterexample61.tla, MC61.out, counterexample61.json E@12:32:37.904\nState 2: state invariant 0 violated. Check the counterexample in: counterexample62.tla, MC62.out, counterexample62.json E@12:32:38.365\nState 2: state invariant 0 violated. Check the counterexample in: counterexample63.tla, MC63.out, counterexample63.json E@12:32:38.809\nState 2: state invariant 0 violated. Check the counterexample in: counterexample64.tla, MC64.out, counterexample64.json E@12:32:39.231\nState 2: state invariant 0 violated. Check the counterexample in: counterexample65.tla, MC65.out, counterexample65.json E@12:32:39.643\nState 2: state invariant 0 violated. Check the counterexample in: counterexample66.tla, MC66.out, counterexample66.json E@12:32:40.085\nStep 2: picking a transition out of 11 transition(s)              I@12:32:40.589\nStep 3: Transition #0 is disabled                                 I@12:32:40.907\nStep 3: Transition #1 is disabled                                 I@12:32:41.444\nStep 3: Transition #2 is disabled                                 I@12:32:41.945\nStep 3: Transition #3 is disabled                                 I@12:32:42.460\nStep 3: Transition #4 is disabled                                 I@12:32:42.869\nStep 3: Transition #5 is disabled                                 I@12:32:43.428\nStep 3: Transition #6 is disabled                                 I@12:32:43.880\nStep 3: Transition #7 is disabled                                 I@12:32:44.309\nStep 3: Transition #8 is disabled                                 I@12:32:44.749\nStep 3: Transition #9 is disabled                                 I@12:32:45.175\nStep 3: Transition #10 is disabled                                I@12:32:45.669\nFound a deadlock. No SMT model.                                   E@12:32:46.122\nFound 66 error(s)                                                 I@12:32:46.123\nThe outcome is: Error                                             I@12:32:46.133\nChecker has found an error                                        I@12:32:46.134\nIt took me 0 days  0 hours  0 min 36 sec                          I@12:32:46.134\nTotal time: 36.419 sec                                            I@12:32:46.134\nEXITCODE: ERROR (12)\n"
      },
      "summary": "Non counterexample errors found in stdout:\nFound a deadlock. No SMT model.                                   E@12:32:46.122"
    }
  }
}
```

**Comment by danwt** [comment] 2021-10-13 11:34
I think we should work this into expected behavior. -n specifies the maximum number of tests to generate only. The pending [PR](https://github.com/informalsystems/modelator/pull/111) updates the --help string.

**Comment by andrey-kuprianov** [comment] 2021-11-14 09:17
@rnbguy could you please address this before 0.4.0 release? Thanks!

**Comment by rnbguy** [comment] 2021-11-17 00:46
`modelator trace -t Test2Steps -n 100 IndicesHistoryTests.tla IndicesTests.cfg` should report as following now.

```
{
  "status": "success",
  "result": {
    "Test2Steps": {
      "Err": {
        "LessNumberOfTracesFound": 66
      }
    }
  }
}
```

**Comment by rnbguy** [comment] 2021-11-17 00:49
Although, I would suggest to keep the number of traces strict, optionally.

**Comment by rnbguy** [comment] 2021-11-17 01:01
This actually resolves #113 as number of traces per test is set to 1 by default.

Does it make sense to force this argument to be positive?

**Comment by danwt** [comment] 2021-11-17 09:03
Just to clarify: the *n* variables should specify a maximum number to generate - generating fewer should not be an error as in general users aren't going to know how many traces can actually be generated beforehand.

**Comment by andrey-kuprianov** [comment] 2021-11-17 09:42
Yes, `n` is just the maximum number; you can never know how many are there.

**Comment by rnbguy** [comment] 2021-11-17 12:46
@danwt @andrey-kuprianov should I rather add an optional argument for user to ask for exactly `n` number of traces?

**Comment by andrey-kuprianov** [comment] 2021-11-17 13:02
But why would we need the exact number? I think the semantics should be:
 - at least 1 trace should always be generated, otherwise it's an error
 - if no `n` is given, then we expect exactly 1
 - if `n` is given, we generate as many as we can, between 1 and `n` inclusive.

We should only describe in the help and in the documentation that `n` is the maximum number, but there can be less

**Comment by rnbguy** [comment] 2021-11-17 14:40
This was a miscommunication. The command from Andrey's first comment produces `success` on my machine. I believe it was an error due to non deterministic situations.

I reverted the changes introducing this error. I am closing this issue as resolved.

**Closed as completed by rnbguy** 2021-11-17 14:40 UTC
Labels: bug
