### ISSUE TITLE
[BUG](0.4.0) Crash 'TLC failure: Encountered an exception while attempt to validate /var/folders/sy/207jjj5...'

### ISSUE THREAD

**Issue by danwt** [informalsystems/modelator#150] opened 2021-12-07 16:43 UTC
Courtesy @adizere 

At https://github.com/informalsystems/modelator/commit/3fe5950a29addba09cdd182ae762767f5232a03f

## Description

Crashes with message like

```
$ RUST_BACKTRACE=1 cargo test -p ibc --test mbt --features=mocks
    Finished test [unoptimized + debuginfo] target(s) in 0.19s
     Running tests/mbt.rs (target/debug/deps/mbt-2b943b43439f60fa)

running 1 test
test mbt ... FAILED

failures:

---- mbt stdout ----
[modelator] Downloading model-checkers...
[modelator] Done!
thread 'mbt' panicked at 'TLC failure: Encountered an exception while attempt to validate /var/folders/sy/207jjj5d7j138ryjs32nbxk00000gn/T/TLC.tla - /var/folders/sy/207jjj5d7j138ryjs32nbxk00000gn/T/TLC.tla (No such file or directory)
', modules/tests/mbt.rs:16:9
```

## Expected behavior

No crash

**Comment by rnbguy** [comment] 2021-12-08 17:23
Duplicate of #148

**Closed by rnbguy** 2021-12-08 17:23 UTC
Labels: bug
